### ISSUE TITLE
Comment for finding METIS and MKL

### ISSUE THREAD

**Issue by Fabian188** [sergiud/SuiteSparse#11]
This is not a bug but probably the information can help users.

To help to find Metis, use -DMETIS_INCLUDE_DIR, -DMETIS_LIBRARY and -DMETIS_ROOT.

In case Intel MKL is not sourced (via setvars) but available use -DBLAS_LIBRARIES and -DLAPACK_LIBRARIES to point to the actual static lib (libmkl_intel_lp64.a for Linux and x86_64 macOS).

Both took me some time to find out.

If there would be discussions enabled in gitlab, not only issues it could remain here. Probably this makes sense in the readme?

**Comment by sergiud** [comment]
This could be indeed useful, thanks. I do, however, have a couple of remarks.

If you specify `METIS_ROOT` you don't need the other two variables and vice versa.

Have you also tried specifying the [BLAS vendor](https://cmake.org/cmake/help/latest/module/FindBLAS.html#blas-lapack-vendors) instead?

**Comment by Fabian188** [comment]
I tried first METIS_INCLUDE_DIR and METIS_LIBRARY which was not sufficient. Hoewever I did not try METIS_ROOT alone.

Also `cmake .. -DBLAS_VENDOR=Intel` is not sufficient, if MKLROOT is not set. 

```
cmake .. -DBLAS_VENDOR=Intel
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindBLAS.cmake:1346 (find_package_handle_standard_args)
  CMakeLists.txt:122 (find_package)
```
Setting MKLROOT has the same effect as sourcing `/opt/intel/oneapi/setvars.sh`. It surprised me, but CMake 3.25.1 seems not to search for /opt/intel/oneapi/mkl/latest but expects MKLROOT - also the documentation indicates this.

I build SuiteSparse via cmake external project. There it is difficult to set an environment variable when configuring a CMake project.

**Comment by sergiud** [comment]
There's a typo in your command line: it's [`BLA_VENDOR`](https://cmake.org/cmake/help/latest/module/FindBLAS.html#input-variables) (without S). `MKLROOT` must be set either way because CMake does not consider `/opt` by default. You also probably want something like `Intel10_64lp` not just `Intel`.

**Comment by Fabian188** [comment]
I first tried BLA_VENDOR but then thought this is the typo. Anyway

```
cmake .. -DBLA_VENDOR=Intel10_64lp
...
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindBLAS.cmake:1346 (find_package_handle_standard_args)
  CMakeLists.txt:122 (find_package)
```
With my approach MKLROOT is not required, which is necessary for my specific situation.

**Comment by sergiud** [comment]
Yes, if you override CMake's search mechanism by explicitly specifying the paths there's no point in providing the root. Therefore, for `BLA_VENDOR` you must also provide the `MKLROOT`. The advantage here is that you do not need to specify each path manually because the CMake find module will ensure the correct and consistent set of files and directories is located.

The corresponding CMake mechanism is actually well [documented](https://cmake.org/cmake/help/latest/command/find_package.html) (also [here](https://cmake.org/cmake/help/latest/variable/PackageName_ROOT.html#variable:%3CPackageName%3E_ROOT)) with some intricacies to be considered separately such as those in `FindBLAS`.

**Comment by Fabian188** [comment]
You do not need to add it to the documentation, it was just a suggestion. 

Probably not many have my situation, which is - as I wrote - that we have systems (e.g. runners) where mkl is installed but not sourced.

When our application builds dependencies (static libs) it already found blas (e.g. MKL) by own mechanisms. It is then always a little annoying to have the dependencies (suitesparse, arpack, lis, ...) also search for a blas which is then usually not needed anyway for the lib but only for demos, tests, examples which I don't build.

**Comment by sergiud** [comment]
The problem with documenting your approach is that it might stop working a couple of CMake versions down the road. Consulting the latest CMake documentation should always be prioritized.

Regarding sourcing: in my experience, you do not actually need to source the MKL scripts. Setting `MKLROOT` to `/opt/intel/mkl` and `BLA_VENDOR` both as environment variables is generally sufficient.

**Comment by sergiud** [comment]
Let me close the issue because it do not feel it is the right approach to mirror excerpts from the CMake documentation.

I might reconsider this in the future though.
