### ISSUE TITLE
Error in compiling on RHEL9 - Segmentation fault (core dumped), when following Makefile in UMFPACK/DEMO

### ISSUE THREAD

**Issue by andreinimarco** [sergiud/SuiteSparse#13]
Hi,

I am trying to compile suitesparse 5.12.0 with metis-5.1.0 on RHEL9, wiht no root privilegies, and encountering the Error in the title when approching to use the Makefile in UMFPACK/DEMO.
Can you help me solving it?

Thanks,
Marco

**Comment by sergiud** [comment]
This project only provides a CMake support layer. I believe your issue belongs to https://github.com/DrTimothyAldenDavis/SuiteSparse as I do not support original makefiles.

**Comment by andreinimarco** [comment]
Thanks for the swift reply.
I will then raise the issue there.
Have a great day.
