### ISSUE TITLE
make failed when build Mongoose  “ undefined reference to `__libc_dl_error_tsd@GLIBC_PRIVATE' ”

### ISSUE THREAD

**Issue by noone3001** [sergiud/SuiteSparse#18]
( cd SuiteSparse_config && make )
make[1]: Entering directory '/home/dftc/Downloads/SuiteSparse/SuiteSparse_config'
make install INSTALL=/home/dftc/Downloads/SuiteSparse
make[2]: Entering directory '/home/dftc/Downloads/SuiteSparse/SuiteSparse_config'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/dftc/Downloads/SuiteSparse/SuiteSparse_config'
make[1]: Leaving directory '/home/dftc/Downloads/SuiteSparse/SuiteSparse_config'
( cd Mongoose  && make CMAKE_OPTIONS='-DCMAKE_INSTALL_PREFIX=/home/dftc/Downloads/SuiteSparse -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc' library )
make[1]: Entering directory '/home/dftc/Downloads/SuiteSparse/Mongoose'
( cd build ; cmake -DCMAKE_INSTALL_PREFIX=/home/dftc/Downloads/SuiteSparse -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc .. ; make --jobs=1 )
-- External ../SuiteSparse_config found.
-- Note: ../SuiteSparse_config must be compiled before compiling Mongoose
-- CMAKE_CXX_COMPILER: GNU
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dftc/Downloads/SuiteSparse/Mongoose/build
make[2]: Entering directory '/home/dftc/Downloads/SuiteSparse/Mongoose/build'
make[3]: Entering directory '/home/dftc/Downloads/SuiteSparse/Mongoose/build'
make[4]: Entering directory '/home/dftc/Downloads/SuiteSparse/Mongoose/build'
make[4]: Leaving directory '/home/dftc/Downloads/SuiteSparse/Mongoose/build'
[ 26%] Built target mongoose_lib
make[4]: Entering directory '/home/dftc/Downloads/SuiteSparse/Mongoose/build'
make[4]: Leaving directory '/home/dftc/Downloads/SuiteSparse/Mongoose/build'
make[4]: Entering directory '/home/dftc/Downloads/SuiteSparse/Mongoose/build'
[ 27%] Linking CXX executable bin/mongoose
/usr/aarch64-linux-gnu-6.3.1/bin/../aarch64-linux-gnu/libc/lib/libpthread.so.0: undefined reference to `__libc_dl_error_tsd@GLIBC_PRIVATE'
collect2: error: ld returned 1 exit status
CMakeFiles/mongoose_exe.dir/build.make:95: recipe for target 'bin/mongoose' failed
make[4]: *** [bin/mongoose] Error 1
make[4]: Leaving directory '/home/dftc/Downloads/SuiteSparse/Mongoose/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mongoose_exe.dir/all' failed
make[3]: *** [CMakeFiles/mongoose_exe.dir/all] Error 2
make[3]: Leaving directory '/home/dftc/Downloads/SuiteSparse/Mongoose/build'
Makefile:140: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/dftc/Downloads/SuiteSparse/Mongoose/build'
Makefile:22: recipe for target 'library' failed
make[1]: *** [library] Error 2
make[1]: Leaving directory '/home/dftc/Downloads/SuiteSparse/Mongoose'
Makefile:128: recipe for target 'library' failed
make: *** [library] Error 2

**Comment by noone3001** [comment]
using v5.8.1

**Comment by sergiud** [comment]
Please report to upstream. Mongoose is not supported.
