### ISSUE TITLE
What is the difference between sergiud/SuiteSparse and DrTimothyAldenDavis/SuiteSparse?

### ISSUE THREAD

**Issue by jiapei-nexera** [sergiud/SuiteSparse#5]
- What is the difference between sergiud/SuiteSparse and DrTimothyAldenDavis/SuiteSparse?

- I believe you've already noticed **GKlib is NOW independent from METIS**, why NOT link the library GKlib in those demos?

**Comment by sergiud** [comment]
* The README provides all the details.
* I don't care about GKlib.
